"""Versioned scenario-provider contracts and exact coverage validation."""

from kamiwaza_sdk.validation.models import (
    AcceleratorFacts,
    CaseResult,
    ClusterFacts,
    CleanupEvidence,
    CleanupResult,
    CoverageIssue,
    CoverageSummary,
    DeploymentFacts,
    FactMatcher,
    FixtureMutation,
    FixtureState,
    HardwareFacts,
    InferenceTarget,
    MeshEdge,
    MeshFacts,
    ResolvedScenario,
    RuntimeCluster,
    RuntimeContext,
    ScenarioCatalog,
    ScenarioDescriptor,
    ScenarioEvidence,
    ScenarioPlan,
    ValidationIntent,
    ValidationProfile,
)
from kamiwaza_sdk.validation.registry import evaluate_coverage, model_digest
from kamiwaza_sdk.validation.provider import (
    FixtureStateWriter,
    ProviderContractError,
    ScenarioProvider,
    validate_fixture_state_snapshots,
)

__all__ = [
    "AcceleratorFacts",
    "CaseResult",
    "ClusterFacts",
    "CleanupEvidence",
    "CleanupResult",
    "CoverageIssue",
    "CoverageSummary",
    "DeploymentFacts",
    "FactMatcher",
    "FixtureMutation",
    "FixtureState",
    "FixtureStateWriter",
    "HardwareFacts",
    "InferenceTarget",
    "MeshEdge",
    "MeshFacts",
    "ProviderContractError",
    "ResolvedScenario",
    "RuntimeCluster",
    "RuntimeContext",
    "ScenarioCatalog",
    "ScenarioDescriptor",
    "ScenarioEvidence",
    "ScenarioPlan",
    "ScenarioProvider",
    "ValidationIntent",
    "ValidationProfile",
    "evaluate_coverage",
    "model_digest",
    "validate_fixture_state_snapshots",
]
